/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicmanagerapp;

/**
 *
 * @author liamf
 */
public class MusicManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicManager
     */
    public MusicManagerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckgrnd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleTB = new javax.swing.JTextField();
        genreDRPDWN = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        addSongBTN = new javax.swing.JButton();
        viewLBL = new javax.swing.JLabel();
        favBTN = new javax.swing.JButton();
        popBTN = new javax.swing.JButton();
        rockBTN = new javax.swing.JButton();
        otherBTN = new javax.swing.JButton();
        popBTN3 = new javax.swing.JButton();
        searchSongBTN = new javax.swing.JButton();
        removeSongBTN = new javax.swing.JButton();
        rearangeSongBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bckgrnd.setBackground(new java.awt.Color(229, 255, 255));
        bckgrnd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("The Music Manager");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Prompt", 1, 14)); // NOI18N
        jLabel2.setText("Song title:");

        jLabel3.setFont(new java.awt.Font("Prompt", 1, 14)); // NOI18N
        jLabel3.setText("Song genre:");

        titleTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTBActionPerformed(evt);
            }
        });

        genreDRPDWN.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        genreDRPDWN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Hip-Hop", "Rock", "Other" }));
        genreDRPDWN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreDRPDWNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        addSongBTN.setBackground(new java.awt.Color(153, 255, 153));
        addSongBTN.setFont(new java.awt.Font("Prompt Bold", 0, 12)); // NOI18N
        addSongBTN.setText("ADD");
        addSongBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addSongBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongBTNActionPerformed(evt);
            }
        });

        viewLBL.setFont(new java.awt.Font("Prompt Semibold", 0, 12)); // NOI18N
        viewLBL.setForeground(new java.awt.Color(153, 153, 153));
        viewLBL.setText("View:");

        favBTN.setBackground(new java.awt.Color(255, 255, 204));
        favBTN.setFont(new java.awt.Font("Prompt Medium", 0, 12)); // NOI18N
        favBTN.setText("Liked");
        favBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favBTNActionPerformed(evt);
            }
        });

        popBTN.setBackground(new java.awt.Color(255, 255, 204));
        popBTN.setFont(new java.awt.Font("Prompt Medium", 0, 12)); // NOI18N
        popBTN.setText("Pop");
        popBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popBTNActionPerformed(evt);
            }
        });

        rockBTN.setBackground(new java.awt.Color(255, 255, 204));
        rockBTN.setFont(new java.awt.Font("Prompt Medium", 0, 12)); // NOI18N
        rockBTN.setText("Rock");
        rockBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockBTNActionPerformed(evt);
            }
        });

        otherBTN.setBackground(new java.awt.Color(255, 255, 204));
        otherBTN.setFont(new java.awt.Font("Prompt Medium", 0, 12)); // NOI18N
        otherBTN.setText("Other");
        otherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherBTNActionPerformed(evt);
            }
        });

        popBTN3.setBackground(new java.awt.Color(255, 255, 204));
        popBTN3.setFont(new java.awt.Font("Prompt Medium", 0, 12)); // NOI18N
        popBTN3.setText("Hip-Hop");
        popBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popBTN3ActionPerformed(evt);
            }
        });

        searchSongBTN.setBackground(new java.awt.Color(204, 204, 255));
        searchSongBTN.setFont(new java.awt.Font("Prompt Bold", 0, 12)); // NOI18N
        searchSongBTN.setText("Search");
        searchSongBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchSongBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSongBTNActionPerformed(evt);
            }
        });

        removeSongBTN.setBackground(new java.awt.Color(255, 102, 102));
        removeSongBTN.setFont(new java.awt.Font("Prompt Bold", 0, 12)); // NOI18N
        removeSongBTN.setText("Remove");
        removeSongBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeSongBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSongBTNActionPerformed(evt);
            }
        });

        rearangeSongBTN.setBackground(new java.awt.Color(255, 204, 102));
        rearangeSongBTN.setFont(new java.awt.Font("Prompt Bold", 0, 12)); // NOI18N
        rearangeSongBTN.setText("Rearange");
        rearangeSongBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rearangeSongBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rearangeSongBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bckgrndLayout = new javax.swing.GroupLayout(bckgrnd);
        bckgrnd.setLayout(bckgrndLayout);
        bckgrndLayout.setHorizontalGroup(
            bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bckgrndLayout.createSequentialGroup()
                .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bckgrndLayout.createSequentialGroup()
                        .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bckgrndLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleTB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genreDRPDWN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bckgrndLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viewLBL)
                                    .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchSongBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addSongBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(removeSongBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rearangeSongBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)))
                        .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bckgrndLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bckgrndLayout.createSequentialGroup()
                                .addComponent(favBTN)
                                .addGap(18, 18, 18)
                                .addComponent(popBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(popBTN3)
                                .addGap(18, 18, 18)
                                .addComponent(rockBTN)
                                .addGap(18, 18, 18)
                                .addComponent(otherBTN))))
                    .addGroup(bckgrndLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        bckgrndLayout.setVerticalGroup(
            bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bckgrndLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bckgrndLayout.createSequentialGroup()
                        .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreDRPDWN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addSongBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchSongBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeSongBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rearangeSongBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLBL)
                    .addComponent(favBTN)
                    .addComponent(popBTN)
                    .addComponent(popBTN3)
                    .addComponent(rockBTN)
                    .addComponent(otherBTN))
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTBActionPerformed

    private void genreDRPDWNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreDRPDWNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreDRPDWNActionPerformed

    private void addSongBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSongBTNActionPerformed

    private void favBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favBTNActionPerformed

    private void popBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popBTNActionPerformed

    private void rockBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rockBTNActionPerformed

    private void otherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherBTNActionPerformed

    private void popBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popBTN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popBTN3ActionPerformed

    private void searchSongBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSongBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSongBTNActionPerformed

    private void removeSongBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSongBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSongBTNActionPerformed

    private void rearangeSongBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rearangeSongBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rearangeSongBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSongBTN;
    private javax.swing.JPanel bckgrnd;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton favBTN;
    private javax.swing.JComboBox<String> genreDRPDWN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton otherBTN;
    private javax.swing.JButton popBTN;
    private javax.swing.JButton popBTN3;
    private javax.swing.JButton rearangeSongBTN;
    private javax.swing.JButton removeSongBTN;
    private javax.swing.JButton rockBTN;
    private javax.swing.JButton searchSongBTN;
    private javax.swing.JTextField titleTB;
    private javax.swing.JLabel viewLBL;
    // End of variables declaration//GEN-END:variables
}
